<?php
ob_start();
session_start();
require_once ('database.php');
require_once ('navbar.php');
?>
<div class="w3-container">
<div class="w3-center w3-third w3-deep-orange w3-padding" style="border:1px solid black;font-size:18px;font-style:arial">
	'Adventure'. At the Woodlands Away we understand that it means different things to different people. For some it’s the chance to mingle with the natives and othersit’s pushing their physical limits, climbing that mountain or chasing a foodie trail. We make it possible for everyone to get out of their comfort zone and #DoTheDIfferent™. Whatever your travel style may be, you’ll find that our itineraries are designed to deliver adventure through activities and experiences hand picked by our specialist team. Now you choose what adventure means to you.If you are bitten by the travel bug and simply can’t wait to get on your next break, we suggest you start here. Browse through our small group trips that are coming up the next few weeks, choose your adventure, pack up and just go.No painful research and planning, no waiting for friends and family to come around and no worries - just a whole lot of fun (that’s the one thing we are totally serious about)!
What makes Woodlands unique in our ability to help customers is more than the sum of our experience and expertise—it’s how we view the world, who we are, how we live and how we work. In fulfilling our mission, it’s not just what we do that matters. It’s what we believe. To learn more about what drives Woodlands, Call Us right now.

</div>
<div class="w3-center w3-third w3-amber w3-padding" style="border:1px solid black;font-size:18px;font-style:arial">
    'Experience'. At the Woodlands Away we comprehend that it implies distinctive things to various individuals. For some it's the opportunity to blend with the locals and othersit's pushing their physical breaking points, climbing that mountain or pursuing a foodie trail. We make it feasible for everybody to escape their customary range of familiarity and #DoTheDIfferent™. Whatever your travel style might be, you'll see that our agendas are intended to convey enterprise through exercises and encounters hand picked by our authority group. Presently you pick what enterprise intends to you.If you are nibbled by the travel bug and just can hardly wait to get on your next break, we propose you begin here. Peruse through our little gathering trips that are coming up the following couple of weeks, pick your experience, pack up and just go.No difficult research and arranging, no sitting tight for loved ones to come around and no stresses - only a ton of fun (that is the one thing we are absolutely genuine about)! What makes Woodlands interesting in our capacity to help clients is more than the total of our experience and mastery—it's the means by which we see the world, our identity, how we live and how we function. In satisfying our central goal, it's not exactly what we do that issues. It's what we accept. To take in more about what drives Woodlands, Call Us at the present time.
</div>
<div class="w3-center w3-third w3-blue w3-padding" style="border:1px solid black;font-size:18px;font-style:arial">
    At the Woodlands Away we fathom that it infers particular things to different people. For some it's the chance to mix with local people and othersit's pushing their physical limits, climbing that mountain or seeking after a foodie trail. We make it possible for everyone to get away from their standard scope of recognition and #DoTheDIfferent™. Whatever your travel style may be, you'll see that our plans are planned to pass on big business through activities and experiences hand picked by our power gathering. By and by you pick what venture expects to you.If you are snacked by the travel bug and simply can barely wait to get on your next break, we propose you start here. Examine through our small assembling trips that are coming up the accompanying couple of weeks, pick your experience, pack up and just go.No troublesome research and organizing, no sitting tight for friends and family to come around and no burdens - just a huge amount of fun (that is the one thing we are totally bona fide about)! What makes Woodlands intriguing in our ability to help customers is more than the aggregate of our experience and dominance—it's the methods by which we see the world, our character, how we live and how we work. In fulfilling our focal objective, it's not precisely what we do that issues. It's what we acknowledge. To take in additional about what drives Woodlands, Call Us right now.
</div>
</div>
<?php
require_once ('footer.php');
